stages:
  - build
  - deploy
build:
  image: docker:latest
  services:
  - docker:dind
  stage: build
  script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD $DOCKER_REGISTRY
    - docker build -t $DOCKER_REGISTRY/simonbreiter/rsstojson .
    - docker push $DOCKER_REGISTRY/simonbreiter/rsstojson
deploy:
  stage: deploy
  image: cdrx/rancher-gitlab-deploy
  script:
   - upgrade --rancher-url $RANCHER_URL --rancher-key $RANCHER_ACCESS_KEY --rancher-secret $RANCHER_SECRET_KEY --stack rsstojson --service rsstojson --no-start-before-stopping
