variables:
  DOCKER_HOST: tcp://docker:2375/

stages:
  - docker
  - deploy

docker:
  stage: docker
  image: docker:latest
  services:
    - docker:dind
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build --tag $CI_REGISTRY/simonbreiter/rsstojson:$CI_COMMIT_SHORT_SHA --tag $CI_REGISTRY/simonbreiter/rsstojson:latest .
    - docker push $CI_REGISTRY/simonbreiter/rsstojson:$CI_COMMIT_SHORT_SHA
    - docker push $CI_REGISTRY/simonbreiter/rsstojson:latest

#docker:arm64:
#    image: jonoh/docker-buildx-qemu
#    stage: docker
#    services:
#      - docker:dind
#    before_script:
#      # Use docker-container driver to allow useful features (push/multi-platform)
#      - docker buildx create --driver docker-container --use
#      - docker buildx inspect --bootstrap
#    script:
#      - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
#      - update-binfmts --enable # Important: Ensures execution of other binary formats is enabled in the kernel
#      - docker buildx build --platform linux/arm64 --tag $CI_REGISTRY/simonbreiter/rsstojson/rsstojson:$CI_COMMIT_SHORT_SHA .
#      - docker push $CI_REGISTRY/simonbreiter/rsstojson/rsstojson:$CI_COMMIT_SHORT_SHA

deploy:
  stage: deploy
  image: dtzar/helm-kubectl:3.1.2
  script:
    - kubectl config set-cluster k8s --server="${K8S_API_URL}"
    - kubectl config set clusters.k8s.certificate-authority-data ${K8S_CA_CERTIFICATE}
    - kubectl config set-credentials gitlab --token="${K8S_TOKEN}"
    - kubectl config set-context default --cluster=k8s --user=gitlab
    - kubectl config use-context default
    - helm upgrade rsstojson chart --namespace rsstojson --set image.tag=${CI_COMMIT_SHORT_SHA}
